# Generated by Django 4.0.5 on 2022-06-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNews', models.IntegerField()),
                ('idComment', models.IntegerField()),
                ('userName', models.CharField(max_length=128)),
                ('msg', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNews', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('text', models.TextField()),
                ('image', models.CharField(max_length=200)),
                ('like', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idComment', models.IntegerField()),
                ('userName', models.CharField(max_length=128)),
                ('msgResp', models.TextField()),
            ],
        ),
    ]
